SELECT
	l.COLUMN_NAME,
	l.DATA_TYPE,
	l.DATA_LENGTH,
	l.DATA_PRECISION,
	c.COMMENTS,
	l.DATA_DEFAULT
FROM
	(
		SELECT
			COLUMN_NAME,
			DATA_TYPE,
			DATA_DEFAULT,
			DATA_LENGTH,
			DATA_PRECISION,
			COLUMN_ID
		FROM
			ALL_TAB_COLUMNS
		WHERE
			(OWNER || '.' || TABLE_NAME) = UPPER('{tableName}')
	) l,
	(
		SELECT
		COLUMN_NAME,
			COMMENTS
		FROM
			ALL_COL_COMMENTS
		WHERE
			(OWNER || '.' || TABLE_NAME) = UPPER('{tableName}')
	) c
WHERE
	l.COLUMN_NAME = c.COLUMN_NAME
ORDER BY
	l.COLUMN_ID